debianrepochecker: reinitialize apt_pkg each time
Without this, the Dir::State::status path is preserved between calls to
this function. Since it's inside a temporary directory that is destroyed
when the function returns, this makes the second and subsequent calls
fail when constructing the apt.Cache():

    apt_pkg.Error: E:Could not open file
    /tmp/tmpvrmj49ts/var/lib/dpkg/status - open (2: No such file or
    directory), E:Problem opening /tmp/tmpvrmj49ts/var/lib/dpkg/status,
    E:The package lists or status file could not be parsed or opened.

This makes the tests pass again (sorry).